export const LOAD_POKEDEX_DATA_REQUEST = 'LOAD_POKEDEX_DATA_REQUEST';
export const LOAD_POKEDEX_DATA_SUCCESS = 'LOAD_POKEDEX_DATA_SUCCESS';
export const LOAD_POKEDEX_DATA_FAIL = 'LOAD_POKEDEX_DATA_FAIL';

export const LOAD_POKEMON_DATA_REQUEST = 'LOAD_POKEMON_DATA_REQUEST';
export const LOAD_POKEMON_DATA_SUCCESS = 'LOAD_POKEMON_DATA_SUCCESS';
export const LOAD_POKEMON_DATA_FAIL = 'LOAD_POKEMON_DATA_FAIL';

export const SEARCH_POKEMON_DATA_REQUEST = 'SEARCH_POKEMON_DATA_REQUEST';
export const SEARCH_POKEMON_DATA_SUCCESS = 'SEARCH_POKEMON_DATA_SUCCESS';
export const SEARCH_POKEMON_DATA_FAIL = 'SEARCH_POKEMON_DATA_FAIL';
